apiVersion: apps/v1
kind: Deployment

metadata:
  name: project5-app
  namespace: project5
  annotations:
    reloader.stakater.com/auto: "true"

spec:
  replicas: 3

  selector:
    matchLabels:
      app: project5-app

  template:
    metadata:
      labels:
        app: project5-app

    spec:
      containers:
        - name: project5-app
          image: ghcr.io/pakilesh/kubernetes-cicd-project:ce3e20f6bc8e4f12940fe15767bdbda8bc53e79a
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: project5-config
            - secretRef:
                name: project5-secret

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
