apiVersion: v1
kind: Service

metadata:
  name: project5-service
  namespace: project5

spec:
  type: NodePort

  selector:
    app: project5-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
